### PR TITLE
Does not work with Tower 2.5 beta

### PR DESCRIPTION
**Pull request by cjlucas**
This doesn't work with the Tower 2.5 beta. No repos are shown in Alfred. The key `filereferenceurl` no longer exists in the bookmarks file.

Basically in `/lib/tower_bookmarks_parser.rb`, just remove `hash.has_key?('filereferenceurl') &&` from line 82 so that we only check for `hash.has_key?('fileurl')`.

### CODE REVIEW

**Comment by cjlucas** [comment]
Try this branch out and see if it makes a difference.

**Comment by mattstein** [comment]
Not for me unfortunately, @cjlucas. I replaced the contents of info.plist, restarted Alfred, verified the settings changes that use command line arguments, and queried with the same (empty) result.

**Comment by cjlucas** [comment]
Do the repositories still list when you dont specify an argument (i.e. just typing "tower" in Alfred)?

**Comment by mattstein** [comment]
No, just the default web search options. No "Search for Tower Repositories...", "Searching Repositories...", or anything to indicate that the workflow is receiving input.

The only time I see anything relevant is upon typing "towe", where I'll see the "Search for Tower Repositories..." menu option. Once "tower" is fully spelled out, it's like the workflow vanishes.

**Comment by sublistic** [comment]
Here's the behaviour @mattstein is describing above - I'm getting the same.

tower-alfred

**Comment by cjlucas** [comment]
Bizarre. The placeholder text ("Search for Tower Repositories...") shows up for me starting with just "t". The workflow doesn't actually get triggered until the entire keyword ("tower") is type, but that is expected.

Edit: Exactly as @sublistic (although mine is working as expected)

Can you pull the latest? I added a debug line ("Received query: ...") that should show up in the debugger.

**Comment by mattstein** [comment]
Sorry, I should have written "up until `towe`"—I'm seeing exactly what @sublistic posted. Will pull now and report back!

**Comment by mattstein** [comment]
Typing out "tower foo"...

```
Starting debug for 'Tower Repositories'

[2016-10-10 17:57:41][STDERR: input.scriptfilter] Received query: ""
[2016-10-10 17:57:44][STDERR: input.scriptfilter] Received query: "f"
[2016-10-10 17:57:44][STDERR: input.scriptfilter] Received query: "fo"
[2016-10-10 17:57:45][STDERR: input.scriptfilter] Received query: "foo"
```

**Comment by cjlucas** [comment]
And when you tried copying the script into a `test.rb` and executing it directly, that worked (on the problematic machine)?

**Comment by mattstein** [comment]
I think you're onto something, @cjlucas! The previous `{query}` version returned populated XML, but the script-argument approach comes back empty:

```
$ ruby test.rb foo
Received query: "foo"
<items/>
``` 

The same is true if I substitute "foo" for something that'd be a legitimate hit: empty response.

**Comment by mattstein** [comment]
```
$ /usr/bin/ruby test.rb amp
Received query: "amp"
All repositories: []
<items/>
```

:(

**Comment by mattstein** [comment]
I think I've got it!

Looking through the parser (and hacking recklessly), it seems that `hash.has_key?('filereferenceurl') && hash.has_key?('fileurl')` is a little dubious because I don't have _any_ `filereferenceurl` keys. Changing that line to `hash.has_key?('filereferenceurl') || hash.has_key?('fileurl')`, everything works just fine again.

**Comment by cjlucas** [comment]
That check was removed in the initial pull request for this issue (09b14ca7fe029a4e7806629bb4eb4ee7abc705ed). Now i'm wondering why the code you have still references `filereferenceurl`.

**Comment by mattstein** [comment]
Ah. It looks like it's still in the prepackaged .alfredworkflow in this repository, which I'm apparently working out of and wrongly assuming it to be the same thing.

**Comment by cjlucas** [comment]
Interesting, even though you were seeing the debug statements I just added.

Anyhoo. I updated the binary. I'll publish it to Packal soon.

**Comment by mattstein** [comment]
I had just pulled the deltas into the working Alfred plugin directory. Looking back at the start of the thread, I'm feeling pretty daft about my "discovery." Thanks for taking the time to troubleshoot, @cjlucas.

**Comment by jolantis** [comment]
Yes, with the updated binary, it's working again! (I was just downloading the master zip)

**Comment by sublistic** [comment]
Awesome! Working for me too - thanks @cjlucas and @mattstein !

**Pull request merged**
